### ISSUE TITLE
KDE - missing "Picture of the day" feature

### ISSUE THREAD

**Issue by T13nou** [endeavouros-team/endeavouros-DE-fixes#1]
Hi EOS team !

Just figured that the "Picture of the day" feature is missing from KDE install.

The install is pretty fresh with the latest everything.

Thanks

**Comment by killajoe** [comment]
not the right place. But anyway..
We do not install all the group of KDE or any other, the EndeavourOS setups are pretty minimal ready to add waht you need instead of installing everything someone could need. 

Will be in `kdeplasma-addons` package https://archlinux.org/packages/extra/x86_64/kdeplasma-addons/
